<?php
/**
 * AssetProfileTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Bridgeman\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bridgeman Images Public Api
 *
 * Last updated on 2019-12-19. Yml version [https://public-api.bridgemanimages.com/swagger.yaml](/swagger.yaml) Note that all endpoints have \"/1.0\" prefix, e.g. \"/1.0/asset/1699997/image/thumbnail\".
 *
 * OpenAPI spec version: 1.1.0-oas3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.14
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Bridgeman\Client;

/**
 * AssetProfileTest Class Doc Comment
 *
 * @category    Class
 * @description AssetProfile
 * @package     Bridgeman\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AssetProfileTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AssetProfile"
     */
    public function testAssetProfile()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "artist"
     */
    public function testPropertyArtist()
    {
    }

    /**
     * Test attribute "artist_birth_date"
     */
    public function testPropertyArtistBirthDate()
    {
    }

    /**
     * Test attribute "artist_id"
     */
    public function testPropertyArtistId()
    {
    }

    /**
     * Test attribute "artist_name_no_birth_date"
     */
    public function testPropertyArtistNameNoBirthDate()
    {
    }

    /**
     * Test attribute "artist_first_name"
     */
    public function testPropertyArtistFirstName()
    {
    }

    /**
     * Test attribute "artist_last_name"
     */
    public function testPropertyArtistLastName()
    {
    }

    /**
     * Test attribute "artist_nationality"
     */
    public function testPropertyArtistNationality()
    {
    }

    /**
     * Test attribute "bal_owned"
     */
    public function testPropertyBalOwned()
    {
    }

    /**
     * Test attribute "black_and_white"
     */
    public function testPropertyBlackAndWhite()
    {
    }

    /**
     * Test attribute "category"
     */
    public function testPropertyCategory()
    {
    }

    /**
     * Test attribute "century_controlled"
     */
    public function testPropertyCenturyControlled()
    {
    }

    /**
     * Test attribute "century_to_controlled"
     */
    public function testPropertyCenturyToControlled()
    {
    }

    /**
     * Test attribute "classification"
     */
    public function testPropertyClassification()
    {
    }

    /**
     * Test attribute "is_colour"
     */
    public function testPropertyIsColour()
    {
    }

    /**
     * Test attribute "comments"
     */
    public function testPropertyComments()
    {
    }

    /**
     * Test attribute "copyright_handler"
     */
    public function testPropertyCopyrightHandler()
    {
    }

    /**
     * Test attribute "copyright_holder"
     */
    public function testPropertyCopyrightHolder()
    {
    }

    /**
     * Test attribute "copyright_status"
     */
    public function testPropertyCopyrightStatus()
    {
    }

    /**
     * Test attribute "creators_duration_over_ride_is_set_to"
     */
    public function testPropertyCreatorsDurationOverRideIsSetTo()
    {
    }

    /**
     * Test attribute "credit_line_compound"
     */
    public function testPropertyCreditLineCompound()
    {
    }

    /**
     * Test attribute "credit_line_short"
     */
    public function testPropertyCreditLineShort()
    {
    }

    /**
     * Test attribute "credit1"
     */
    public function testPropertyCredit1()
    {
    }

    /**
     * Test attribute "credit2"
     */
    public function testPropertyCredit2()
    {
    }

    /**
     * Test attribute "copyright_death_date"
     */
    public function testPropertyCopyrightDeathDate()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "dimensions"
     */
    public function testPropertyDimensions()
    {
    }

    /**
     * Test attribute "show_on_web"
     */
    public function testPropertyShowOnWeb()
    {
    }

    /**
     * Test attribute "rgb_blue"
     */
    public function testPropertyRgbBlue()
    {
    }

    /**
     * Test attribute "rgb_green"
     */
    public function testPropertyRgbGreen()
    {
    }

    /**
     * Test attribute "rgb_red"
     */
    public function testPropertyRgbRed()
    {
    }

    /**
     * Test attribute "footage"
     */
    public function testPropertyFootage()
    {
    }

    /**
     * Test attribute "hires_available"
     */
    public function testPropertyHiresAvailable()
    {
    }

    /**
     * Test attribute "hr_size"
     */
    public function testPropertyHrSize()
    {
    }

    /**
     * Test attribute "horizontal"
     */
    public function testPropertyHorizontal()
    {
    }

    /**
     * Test attribute "pixel_height"
     */
    public function testPropertyPixelHeight()
    {
    }

    /**
     * Test attribute "pixel_width"
     */
    public function testPropertyPixelWidth()
    {
    }

    /**
     * Test attribute "keywords"
     */
    public function testPropertyKeywords()
    {
    }

    /**
     * Test attribute "location"
     */
    public function testPropertyLocation()
    {
    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {
    }

    /**
     * Test attribute "supplier_name"
     */
    public function testPropertySupplierName()
    {
    }

    /**
     * Test attribute "supplier_prefix"
     */
    public function testPropertySupplierPrefix()
    {
    }

    /**
     * Test attribute "supplier_reference"
     */
    public function testPropertySupplierReference()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "year_controlled"
     */
    public function testPropertyYearControlled()
    {
    }

    /**
     * Test attribute "year_to_controlled"
     */
    public function testPropertyYearToControlled()
    {
    }

    /**
     * Test attribute "year_controlled_circa"
     */
    public function testPropertyYearControlledCirca()
    {
    }

    /**
     * Test attribute "year_to_controlled_circa"
     */
    public function testPropertyYearToControlledCirca()
    {
    }

    /**
     * Test attribute "location_id"
     */
    public function testPropertyLocationId()
    {
    }

    /**
     * Test attribute "num_lightboxes"
     */
    public function testPropertyNumLightboxes()
    {
    }

    /**
     * Test attribute "medium"
     */
    public function testPropertyMedium()
    {
    }

    /**
     * Test attribute "asset_is_illustration"
     */
    public function testPropertyAssetIsIllustration()
    {
    }

    /**
     * Test attribute "asset_is_object"
     */
    public function testPropertyAssetIsObject()
    {
    }

    /**
     * Test attribute "asset_is_photo"
     */
    public function testPropertyAssetIsPhoto()
    {
    }

    /**
     * Test attribute "asset_is_film_still"
     */
    public function testPropertyAssetIsFilmStill()
    {
    }

    /**
     * Test attribute "restriction"
     */
    public function testPropertyRestriction()
    {
    }

    /**
     * Test attribute "source"
     */
    public function testPropertySource()
    {
    }

    /**
     * Test attribute "special_instruction"
     */
    public function testPropertySpecialInstruction()
    {
    }

    /**
     * Test attribute "reason_withdrawn"
     */
    public function testPropertyReasonWithdrawn()
    {
    }

    /**
     * Test attribute "thumbnail_url"
     */
    public function testPropertyThumbnailUrl()
    {
    }

    /**
     * Test attribute "website_url"
     */
    public function testPropertyWebsiteUrl()
    {
    }
}
